name: airogs
channels:
  - pytorch
  - conda-forge
  #- defaults

dependencies:
  - python>=3.9
  - matplotlib
  - pandas>1.0.0
  - jupyter
  - ipython
  # Core scientific python
  - numpy
  - opencv
  - tqdm
  - transformers
  # PyTorch for deep learning
  - pytorch
  - torchvision
  # - cudatoolkit=11.3
  - pytorch-lightning
  - pillow