name: airogs
channels:
  - conda-forge
  - pytorch
  #- defaults

dependencies:
  - python>=3.9
  - matplotlib
  - pandas>1.0.0
  - jupyter
  - ipython
  # Core scientific python
  - numpy
  - conda-forge::opencv
  - conda-forge::tqdm
  - conda-forge::transformers
  - torchvision
  - pytorch-gpu
  - conda-forge::pytorch-lightning
  - conda-forge::pillow