name: airogs
channels:
  - conda-forge
  - pytorch
  #- defaults

dependencies:
  - python>=3.9
  - matplotlib
  - pandas>1.0.0
  - jupyter
  - ipython
  # Core scientific python
  - numpy
  - conda-forge::opencv
  - conda-forge::tqdm
  - conda-forge::transformers
  # PyTorch for deep learning
  - pytorch::pytorch-gpu
  - pytorch::torchvision
  - cudatoolkit=11.3
  - conda-forge::pytorch-lightning
  - conda-forge::pillow  