DATA_CROP_ENLARGMENT_FACTOR: 1.4283556979968262
DATA_MAX_OD_DIAMETER_PROP: 2.0
adamw_amsgrad: false
aug_rot_degrees: 0
aug_scale: 0.0
aug_translate: 0.0
backbone: tv-224-swin_b.IMAGENET1K_V1
batch_size: 64
class_balancing: none
cls_label_file: ./data/dev_labels.csv
data_dir: ./data/yolo_baseline_cfp_od_crop_OD_f2.0
dropout: 0.0
equalize: 'no'
es_mode: max
es_patience: 3
es_var: val_partial_auroc
experiment_name: h0b29272b94d2f51a_s1_f0
focal_loss_alpha: 0.5
focal_loss_gamma: 2
gpus: -1
label_smoothing: 0.0
lr: 5.0e-05
lr_training_epochs: 20
lr_warmup_epochs: 1
od_crop_factor: 1.2
optimizer: adamw
predict_checkpoint: null
seed: 1
sgd_momentum: 0.9
sgd_nesterov: false
split_num_val_folds: 5
split_test_prop: 0.2
split_val_fold_idx: 0
use_lr_scheduler: false
weight_decay_factor: 0
weights_summary: full
